# Generated by Django 6.1 on 2026-08-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfigCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(editable=False, max_length=64, unique=True, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Категория глобальных настроек',
                'verbose_name_plural': 'Категории глобальных настроек',
                'db_table': 'global_config_category',
                'ordering': ['id'],
                'default_permissions': ['change', 'view'],
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('value_type', models.SmallIntegerField(choices=[(0, 'String'), (1, 'Boolean'), (2, 'Float'), (3, 'Decimal'), (4, 'Integer'), (5, 'Secure'), (6, 'Date'), (7, 'Time'), (8, 'DateTime'), (9, 'String Array'), (10, 'Integer Array'), (11, 'Float Array'), (12, 'Decimal Array'), (13, 'Color'), (14, 'String Choices'), (15, 'Integer Choices'), (16, 'Float Choices'), (17, 'Decimal Choices'), (18, 'Json'), (19, 'Integer Multiple Choices'), (20, 'String Multiple Choices'), (21, 'Float Multiple Choices'), (22, 'UUID')], verbose_name='Тип значения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_read_only', models.BooleanField(default=False, verbose_name='Только для чтения')),
                ('nullable', models.BooleanField(default=False, verbose_name='Может ли быть не заполнено')),
                ('variables', models.JSONField(blank=True, null=True, verbose_name='Возможные значения')),
                ('is_always_update', models.BooleanField(default=False, help_text='Только для типов данных с выбором значения.', verbose_name='Всегда обновляемый')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='django_gc.globalconfigcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Глобальная настройка',
                'verbose_name_plural': 'Глобальные настройки',
                'db_table': 'global_config',
                'default_permissions': ['change', 'view'],
            },
        ),
    ]
