# Generated by Django 6.1 on 2026-09-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalconfig',
            options={'default_permissions': ['change', 'view'], 'verbose_name': 'Глобальная конфигурация', 'verbose_name_plural': 'Глобальные конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='globalconfigcategory',
            options={'default_permissions': ['change', 'view'], 'ordering': ['id'], 'verbose_name': 'Категория глобальных конфигураций', 'verbose_name_plural': 'Категории глобальных конфигураций'},
        ),
        migrations.RemoveField(
            model_name='globalconfigcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='globalconfigcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='globalconfigcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='globalconfigcategory',
            name='updated_at',
        ),
    ]
